{
	"agentID":	[
		{
			"firstName": "First",
			"lastName": "Last",
      "userAPIKey": "12345"
		}
	],

  "logSettings": 
    {
# Default log location is user desktop
      "logLocation": "os.path.expanduser("~/Desktop"),
# Default new cycle date is 1st of the month
      "newCycleDate": "1"
    }
}